/*
 * Copyright (C) 2019 Toshiba Corporation
 * SPDX-License-Identifier: Apache-2.0
 */

export enum EShapeActionValueMiscType {
	INPUT_TEXT,
	INPUT_INTEGER,
	INPUT_REAL,
	EMIT_EVENT,
	WRITE_BOTH,
	WRITE_LOCAL,
	WRITE_REMOTE,
	HTML_ELEMENT,
	HTML_ELEMENT_WITHOUT_POINTER_EVENTS,
	LAYER_SHOW_HIDE,
	LAYER_GESTURE,
	GESTURE
}
