/*
 * Copyright (C) 2019 Toshiba Corporation
 * SPDX-License-Identifier: Apache-2.0
 */

export enum EShapeStrokeStyle {
	NONE = 0,

	NON_SCALING_WIDTH_WHEN_EXPANDING = 2,
	NON_SCALING_WIDTH_WHEN_SHRINKING = 4,
	NON_SCALING_WIDTH = NON_SCALING_WIDTH_WHEN_EXPANDING | NON_SCALING_WIDTH_WHEN_SHRINKING,
	NON_SCALING_DOT_AND_DASH = 8,
	NON_SCALING = NON_SCALING_WIDTH | NON_SCALING_DOT_AND_DASH,
	NON_SCALING_MASK = NON_SCALING,

	DOTTED = 16,
	DOTTED_DENSELY = 32,
	DOTTED_LOOSELY = 64,
	DOTTED_MASK = DOTTED | DOTTED_DENSELY | DOTTED_LOOSELY,

	DASHED = 128,
	DASHED_DENSELY = 256,
	DASHED_LOOSELY = 512,
	DASHED_MASK = DASHED | DASHED_DENSELY | DASHED_LOOSELY
}
