/*
 * Copyright (C) 2019 Toshiba Corporation
 * SPDX-License-Identifier: Apache-2.0
 */

export enum EShapeType {
	CIRCLE,
	RECTANGLE,
	RECTANGLE_ROUNDED,
	TRIANGLE,
	TRIANGLE_ROUNDED,
	LINE,
	IMAGE,
	IMAGE_SDF,
	GROUP,
	BAR,
	LABEL,
	NULL,
	GROUP_SHADOWED,
	LINE_OF_CIRCLES,
	LINE_OF_RECTANGLES,
	LINE_OF_RECTANGLE_ROUNDEDS,
	LINE_OF_TRIANGLES,
	LINE_OF_TRIANGLE_ROUNDEDS,
	EMBEDDED,
	LAYER,
	EXTENSION = 1000
}
